import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "../../components/header";
import Footer from "@/app/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: "next.js, typescript, tailwindcss",
};

export default function BlogLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className={inter.className}>
      <Nav />
      {children}
      <Footer />
    </section>
  );
}
